### PR TITLE
Restructured to avoid code duplication

### PR DESCRIPTION
**Pull request by noppej**

### CODE REVIEW

**Comment by noppej** [comment]
@Tiwalun ... please approve this, so that I can reference  the latest from https://github.com/probe-rs/probe-rs/pull/1056#

**Review by Tiwalun — APPROVED** [review]
LGTM :+1: 

Maybe we should consider adding the `Cargo.lock` file to the repository as well? That would help with reproducibility, if we use the compiled binaries from here in tests.

**Comment by noppej** [comment]
> LGTM 👍
> 
> Maybe we should consider adding the `Cargo.lock` file to the repository as well? That would help with reproducibility, if we use the compiled binaries from here in tests.

Thinking about it ... for now, i have just copied the binary over to the other repo. I'd like to be able to keep this repo in a state where we can update dependencies and test against latest versions of them. I need to think how we can solve the problem of keeping memory addresses, etc. up to date in the other test cases. If we could have hardware (or sim) available for testing, then I think it is might to be a case of having test cases that doesn't rely on a specific memory address, but rather compares the actual instructions at the breakpoint locations to make sure they are stopped on the expected instruction.

**Comment by Tiwalun** [comment]
The lock file shouldn't prevent updates, you just have to update the lock file when you want to use newer versions of the dependencies.

But then you could either link to a commit, or tag it, and then you could use the lock file to reproduce that binary. Without a lock file, that's not really possible.

**Pull request merged**
